### ISSUE TITLE
cannot install with bower

### ISSUE THREAD

**Issue by ChrisPiechowicz** [scottdorman/bootstrap-flat#3]
How can I install it using bower?

It doesn't work:

bower install bootstrap-flat
bower install bootstrap-flat-sass

**Comment by ChrisPiechowicz** [comment]
finally i did this: bower install https://github.com/scottdorman/bootstrap-flat-sass

**Comment by scottdorman** [comment]
The bower.json files weren't committed properly to the repos, so the packages never got registered with bower. Please try it now.

**Comment by ChrisPiechowicz** [comment]
Now is OK!
Thank you Scott :-)
