### ISSUE TITLE
Nuget packages outdated

### ISSUE THREAD

**Issue by Jogai** [scottdorman/bootstrap-flat#6]
Both packages look outdated. Any plans to maintain them?
If you do I have a wish:
Use the Bootstrap.Flat package to distribute the Compiled and minified CSS, JavaScript, and fonts.
Use the Twitter.Bootstrap.Flat package to distribute the source files and use Twitter.Bootstrap.Less as a dependency for developers that use less.

**Comment by scottdorman** [comment]
The Twitter.Bootstrap.Flat package was actually deprecated in favor of the Bootstrap.Flat package. That package has been updated with the most recent release. There is also now a Bootstrap.Flat.Less package to distribute just the source files (and has a dependency on Twitter.Bootstrap.Less).

**Comment by Jogai** [comment]
Great! Thanks.
